apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
  labels:
    my.volume: test
    my.stage: dev
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/doron/my-volume"