apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-flask
  template:
    metadata:
      name: simple-flask 
      labels:
        creation_method: manual
        env: prod
        app: simple-flask
      annotations:
        description: "This is a very simple python flask image"
    spec:
      containers:
        - image: doroncomputer/simple_flask
          name: simple-flask
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
          envFrom:
          -   configMapRef:
                name: simple-flask-config
          
 